# <center>Laboratorium 1<br>Metody Numeryczne</center>

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [37]:
from main import *

import numpy as np
import scipy

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [38]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)

Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.

In [39]:
a = cylinder_area(1,1)
print(a)
a = cylinder_area(1,"1")
print(a)
a = cylinder_area('b',1)

print(a)

12.566370614359172
12.566370614359172
nan


***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji *[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)* oraz *[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)*. Wypisz go i przeanalizuj otrzymane rezultaty.

In [40]:
ciag_1 = np.arange(0,10,0.1)
ciag_2 = np.linspace(0,10,13)
print(ciag_1)
print(ciag_2)
"""
Analiza: 
arrange odgórnie zdefiniowany krok
linspace dzielenie przedziału na n równych części
"""

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[ 0.          0.83333333  1.66666667  2.5         3.33333333  4.16666667
  5.          5.83333333  6.66666667  7.5         8.33333333  9.16666667
 10.        ]


'\nAnaliza: \narrange odgórnie zdefiniowany krok\nlinspace dzielenie przedziału na n równych części\n'

***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

In [41]:
print(fib(3))
print(fib("h"))

[[1 1 2]]
None


***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

In [42]:
import numpy as np # słowo kluczowe "as" oznacza przesłania nazwę numpy i pozwala  
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))

Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]


In [43]:
print("1-wszy przyklad(dla wartości 1): \n")
for i in matrix_calculations(1):
    print(f"{i}\n")
print("2-gi przyklad(dla warości niezdatnej do konwersji): \n")
print(matrix_calculations("fjwe"))
print("\n3-ci przyklad(dla wartości datnej do konwersji): \n")
for i in matrix_calculations("1"):
    print(f"{i}\n")

1-wszy przyklad(dla wartości 1): 

[[ 0.   1.  -1. ]
 [ 0.5  0.   0.5]
 [-0.5  1.  -0.5]]

[[ 1  0 -1]
 [ 1  1  1]
 [-1  1  1]]

-2.0

2-gi przyklad(dla warości niezdatnej do konwersji): 



TypeError: bad operand type for unary -: 'str'

Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.

***Zadanie 5.***  
Stwórz w noataniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie


In [ ]:
# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]


In [ ]:
M = np.array([[3,1,-2,4],[0,1,1,5],[-2,1,1,6],[4,3,0,1]])
print(M)
#(pierwsza kolumna to kolumna o indeksie [0])
print(f"M(1,1):{M[0][0]}\nM(3,3):{M[2][2]}\nM(3,2):{M[2][1]}")
w1 = M[:,2]
print(f"elementy w1:\n{w1}")
w2 = M[1,:]
print(f"elementy w2:\n{w2}")

[[ 3  1 -2  4]
 [ 0  1  1  5]
 [-2  1  1  6]
 [ 4  3  0  1]]
M(1,1):3
M(3,3):1
M(3,2):1
elementy w1:
[-2  1  1  0]
elementy w2:
[0 1 1 5]


Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

In [ ]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


In [ ]:
#przykladowa macierz gdzie m i n należą do zbioru <3,7>
print(custom_matrix(4,6))

[[0 1 2 3 4 5]
 [1 1 2 3 4 5]
 [2 2 2 3 4 5]
 [3 3 3 3 4 5]]


***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

In [ ]:
v1 = np.array([[1],[3],[13]])
v2 = np.array([[8],[5],[-2]])
print(f"1) {4*v1}")
print(f"2) {-v2 + np.array([[2],[2],[2]])}")
print(f"3) warunkiem na mnożenie caushiego jest fakt posiadania przez macierz drugą liczby kolumn odpowiadającą ilości wierszy macierzy pierwszej\n z tego powodu trzeba przyjąć że któraś z macierzy jest transponowana \n {v1*(v2.T)}")
print(f"4) {v1*v2}")


NameError: name 'np' is not defined

***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

In [ ]:
M1 = np.array([[1,-7,3],[-12,3,4],[5,13,-3]])
print(f"1) {3*M1}")
print(f"2) {3*M1 + np.ones([3,3])}")
print(f"3) {M1.T}")
print(f"4) {np.matmul(M1,v1)}")
print(f"5) {np.matmul(v2.T,M1)}")

1) [[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]]
2) [[  4. -20.  10.]
 [-35.  10.  13.]
 [ 16.  40.  -8.]]
3) [[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]]
4) [[19]
 [49]
 [ 5]]
5) [[-62 -67  50]]


# Wnioski:

nie było większych problemów ze zrozumieniem biblioteki numpy.

problemem okazały się wymagania do zadań które według mnie nie do końca określały wymagania co do sprawdzenia poprawności argumentów funkcji. np. zmienną którą dało sie rzutować na typ int bez żadnej straty informacji (informacja w uwagach) nie mogła być rzutowana (według testów) co było pewnym niedopowiedzeniem. 

wszystkie funkcje działają (przechodzą testy) ze względu na (mam nadzieję) dobrą implementację.

Uwagi

jedynym problemem w ćwiczeniu okazały się nektóre testy jednostkowe:

* jeden z testów jednostkowych do zad 3 (podobnie jak w innych zadaniach) określa że 10.0 (typ float) nie może być zastosowana jako argument funkcji fib chociaż bez straty informacji można go zrzutować na typ int. (treść zad. 3)

* ostatni z testów jednostkowych do zad 3 określa że zwracany array ma być typu np.array([[int]]) co jest poniekąd sprzeczne z poprzednimi testami w których oczekiwane wartości są typu np.array([int]) 


Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)